steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    # No 'dir' field is needed here because Dockerfile is at the root
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']

  # Step 2: Push the built Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app']

  # Step 3: Deploy the image from GCR to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/my-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: 'CLOUD_LOGGING_ONLY'